name: mec_attendance
description: A new Flutter project.
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  beautifulsoup: ^0.0.1
  shared_preferences: ^0.5.3+4
  retry: ^3.0.0+1
  url_launcher: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2+1"

flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true


flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/mec.png


  # fonts:
    # - family: MyFont
    #   fonts:
    #     - asset: assets/cfont.ttf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
